networks:
  1panel-network:
    external: true
services:
  chrome:
    container_name: csdn
    image: csdn:0.3
    network_mode: host
    # networks:
    #   - 1panel-network
    env_file:
      - .env
    restart: no
    command: python /app/main.py
    volumes:
      - .:/app
    